# Generated by Django 6.0.6 on 2026-06-21 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='authenticationsession',
            new_name='user_revoked_expires_idx',
            old_name='authentication_user_revoked_expires_idx',
        ),
    ]
