# Generated by Django 6.0.6 on 2026-06-27 22:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Concluida'), ('ARCHIVED', 'Arquivada')], default='DRAFT', max_length=30)),
                ('current_movement', models.CharField(choices=[('BOUNDGROUND', 'Boundground'), ('LABOR', 'Labor'), ('ECHO', 'Echo'), ('NOISECATCH', 'Noisecatch'), ('DRAWBRIDGE', 'Drawbridge'), ('ENHANCE', 'Enhance'), ('SIGHTLINE', 'Sightline')], default='BOUNDGROUND', max_length=30)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_blaves', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blaves', to='organizations.organization')),
            ],
            options={
                'db_table': 'blaves',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlaveMovementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.CharField(choices=[('BOUNDGROUND', 'Boundground'), ('LABOR', 'Labor'), ('ECHO', 'Echo'), ('NOISECATCH', 'Noisecatch'), ('DRAWBRIDGE', 'Drawbridge'), ('ENHANCE', 'Enhance'), ('SIGHTLINE', 'Sightline')], max_length=30)),
                ('status', models.CharField(choices=[('LOCKED', 'Bloqueado'), ('ACTIVE', 'Ativo'), ('COMPLETED', 'Concluido'), ('INVALIDATED', 'Invalidado')], default='LOCKED', max_length=30)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('blave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_statuses', to='blendes.blave')),
            ],
            options={
                'db_table': 'blave_movement_status',
                'ordering': ['blave', 'movement'],
            },
        ),
        migrations.CreateModel(
            name='BlaveRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('movement', models.CharField(choices=[('BOUNDGROUND', 'Boundground'), ('LABOR', 'Labor'), ('ECHO', 'Echo'), ('NOISECATCH', 'Noisecatch'), ('DRAWBRIDGE', 'Drawbridge'), ('ENHANCE', 'Enhance'), ('SIGHTLINE', 'Sightline')], max_length=30)),
                ('snapshot_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='blendes.blave')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_blave_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blave_revision',
                'ordering': ['blave', '-revision_number'],
            },
        ),
        migrations.AddIndex(
            model_name='blave',
            index=models.Index(fields=['organization', 'status'], name='blaves_organiz_b93838_idx'),
        ),
        migrations.AddIndex(
            model_name='blave',
            index=models.Index(fields=['organization', 'current_movement'], name='blaves_organiz_0daa2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='blavemovementstatus',
            constraint=models.UniqueConstraint(fields=('blave', 'movement'), name='uq_blave_movement_status'),
        ),
        migrations.AddConstraint(
            model_name='blaverevision',
            constraint=models.UniqueConstraint(fields=('blave', 'revision_number'), name='uq_blave_revision_number'),
        ),
    ]
