# Generated by Django 6.0.6 on 2026-06-28 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacetDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facet', models.CharField(choices=[('WHAT', 'What'), ('WHY', 'Why'), ('WHEN', 'When'), ('WHO', 'Who'), ('WITH', 'With'), ('WHEREBY', 'Whereby'), ('IN', 'in'), ('OUT', 'Out')], db_index=True, default='WHAT', max_length=8)),
                ('generate_risk', models.BooleanField(default=True)),
                ('value', models.CharField(max_length=255)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'facet_descriptions',
            },
        ),
        migrations.CreateModel(
            name='KrefPratice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pratice', models.CharField(db_index=True, max_length=255)),
                ('references', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kref_pratices',
                'ordering': ['created_at', 'pratice'],
            },
        ),
        migrations.CreateModel(
            name='Blave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Concluida'), ('ARCHIVED', 'Arquivada')], default='DRAFT', max_length=30)),
                ('current_movement', models.CharField(choices=[('BOUNDGROUND', 'Boundground'), ('LABOR', 'Labor'), ('ECHO', 'Echo'), ('NOISECATCH', 'Noisecatch'), ('DRAWBRIDGE', 'Drawbridge'), ('ENHANCE', 'Enhance'), ('SIGHTLINE', 'Sightline')], default='BOUNDGROUND', max_length=30)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_blaves', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blaves', to='organizations.organization')),
            ],
            options={
                'db_table': 'blave',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlaveMovements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.CharField(choices=[('BOUNDGROUND', 'Boundground'), ('LABOR', 'Labor'), ('ECHO', 'Echo'), ('NOISECATCH', 'Noisecatch'), ('DRAWBRIDGE', 'Drawbridge'), ('ENHANCE', 'Enhance'), ('SIGHTLINE', 'Sightline')], max_length=30)),
                ('status', models.CharField(choices=[('LOCKED', 'Bloqueado'), ('ACTIVE', 'Ativo'), ('COMPLETED', 'Concluido'), ('INVALIDATED', 'Invalidado')], default='LOCKED', max_length=30)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_at', models.DateField(blank=True, null=True)),
                ('blave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_statuses', to='blendes_flow.blave')),
            ],
            options={
                'db_table': 'blave_movements',
                'ordering': ['blave', 'movement'],
            },
        ),
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('blave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boundary', to='blendes_flow.blave')),
                ('outer_boundary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inner_boundaries', to='blendes_flow.boundary')),
            ],
            options={
                'db_table': 'boundaries',
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConcreteAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField()),
                ('kref_pratice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='concrete_action', to='blendes_flow.krefpratice')),
            ],
            options={
                'db_table': 'concrete_actions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mixpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('concrete_action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mixpoint', to='blendes_flow.concreteaction')),
            ],
            options={
                'db_table': 'mixpoints',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formated_text', models.CharField(max_length=255)),
                ('strategic_impact', models.CharField(max_length=255)),
                ('operational_impact', models.CharField(max_length=255)),
                ('tactical_impact', models.CharField(max_length=255)),
                ('priority_position', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('facet_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='blendes_flow.facetdescription')),
            ],
            options={
                'db_table': 'risks',
                'ordering': ['created_at', 'priority_position'],
            },
        ),
        migrations.AddField(
            model_name='krefpratice',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kref_pratices', to='blendes_flow.risk'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('ROLE', 'Role'), ('GROUP', 'Group')], default='ROLE', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleExecutionSchapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schapter_executions', to='blendes_flow.role')),
            ],
            options={
                'db_table': 'role_execution_schapter',
            },
        ),
        migrations.CreateModel(
            name='Schapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schapters', to='blendes_flow.boundary')),
                ('roles', models.ManyToManyField(blank=True, related_name='schapters', through='blendes_flow.RoleExecutionSchapter', to='blendes_flow.role')),
            ],
            options={
                'db_table': 'schapters',
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='roleexecutionschapter',
            name='schapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_executions', to='blendes_flow.schapter'),
        ),
        migrations.AddField(
            model_name='facetdescription',
            name='schapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facet_descriptions', to='blendes_flow.schapter'),
        ),
        migrations.AddIndex(
            model_name='blave',
            index=models.Index(fields=['organization', 'status'], name='blave_organiz_b9d676_idx'),
        ),
        migrations.AddIndex(
            model_name='blave',
            index=models.Index(fields=['organization', 'current_movement'], name='blave_organiz_3c7e42_idx'),
        ),
        migrations.AddConstraint(
            model_name='blavemovements',
            constraint=models.UniqueConstraint(fields=('blave', 'movement'), name='uq_blave_movement_status'),
        ),
        migrations.AddConstraint(
            model_name='boundary',
            constraint=models.UniqueConstraint(fields=('name', 'blave'), name='uq_boundary_blave_name'),
        ),
        migrations.AddConstraint(
            model_name='risk',
            constraint=models.UniqueConstraint(fields=('facet_description', 'priority_position'), name='uq_risk_priority_per_facet_description'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='uq_role_organization_name'),
        ),
        migrations.AddConstraint(
            model_name='schapter',
            constraint=models.UniqueConstraint(fields=('name', 'boundary'), name='uq_schapter_name'),
        ),
        migrations.AddConstraint(
            model_name='roleexecutionschapter',
            constraint=models.UniqueConstraint(fields=('role', 'schapter'), name='uq_role_execution_schapter'),
        ),
        migrations.AddConstraint(
            model_name='facetdescription',
            constraint=models.UniqueConstraint(fields=('schapter', 'facet'), name='uq_schapter_facet'),
        ),
    ]
