# Generated by Codex on 2026-06-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blendes_flow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boundary",
            name="blave",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boundaries",
                to="blendes_flow.blave",
            ),
        ),
    ]
