# Generated by Codex on 2026-06-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blendes_flow", "0002_boundary_blave_many"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mixpoint",
            name="concrete_action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mixpoints",
                to="blendes_flow.concreteaction",
            ),
        ),
    ]
