# Generated by Codex on 2026-07-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blendes_flow", "0003_mixpoint_concrete_action_many"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestedBoundary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "suggested_boundaries",
                "ordering": ["name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SuggestedSchapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "suggested_schapters",
                "ordering": ["name", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="blave",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="boundary",
            name="suggested_boundary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boundaries",
                to="blendes_flow.suggestedboundary",
            ),
        ),
        migrations.AddField(
            model_name="schapter",
            name="suggested_schapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schapters",
                to="blendes_flow.suggestedschapter",
            ),
        ),
        migrations.AddIndex(
            model_name="suggestedboundary",
            index=models.Index(fields=["name"], name="suggested_b_name_1f7c7e_idx"),
        ),
        migrations.AddIndex(
            model_name="suggestedschapter",
            index=models.Index(fields=["name"], name="suggested_s_name_bc7c19_idx"),
        ),
        migrations.AddConstraint(
            model_name="suggestedboundary",
            constraint=models.UniqueConstraint(
                fields=("name",),
                name="uq_suggested_boundary_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="suggestedschapter",
            constraint=models.UniqueConstraint(
                fields=("name",),
                name="uq_suggested_schapter_name",
            ),
        ),
    ]
